name: CI

on:
  push:
    branches: 
      - master

jobs:
  checkout:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Run antora
      uses: docker://antora/antora:2.2.0
      with:
        entrypoint: /bin/sh
        volumes: asd
        args: antora github-pages.yml 
    - name: Run a one-line script
      run: antora $GITHUB_WORKSPACE/github-pages.yml
    
