name: CI

on:
  push:
    branches: 
      - master

jobs:
  checkout:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    
  build:
    runs-on: ubuntu-18.04
    container: antora/antora:2.2.0
    steps:
    - name: List files
      run: ls -lR .
    - name: List root
      run: ls -lR /
    - name: env
      run: env
    - name: Run a one-line script
      run: antora $GITHUB_WORKSPACE/github-pages.yml
    
